# Generated by Django 2.2.13 on 2020-10-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importData', models.FileField(upload_to='inventory/')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('csv_file', models.FileField(blank=True, upload_to='inventory/')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='semester',
            field=models.CharField(default=False, max_length=255, null=True),
        ),
    ]
