# Generated by Django 2.2.13 on 2020-10-05 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Chairman_Framework', '0001_initial'),
        ('Teacher_Framework', '0002_auto_20201005_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Chairman_Framework.CLO'),
        ),
    ]
