# Generated by Django 2.2.13 on 2020-10-06 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher_Framework', '0003_auto_20201005_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Graded_Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('marks', models.IntegerField(default=0)),
                ('graded', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher_Framework.Question')),
            ],
        ),
    ]
