# Generated by Django 2.2.13 on 2020-10-06 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Teacher_Framework', '0004_graded_graded_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graded_questions',
            old_name='question_text',
            new_name='clo_code',
        ),
        migrations.AddField(
            model_name='graded',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_cr', to=settings.AUTH_USER_MODEL),
        ),
    ]
