# Generated by Django 2.2.13 on 2020-10-06 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher_Framework', '0005_auto_20201006_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graded_questions',
            name='graded',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher_Framework.Graded'),
        ),
    ]
