# Generated by Django 2.2.13 on 2020-10-06 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Teacher_Framework', '0007_auto_20201006_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice_Graded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question_Graded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_cr', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='graded_questions',
            name='graded_assignment',
        ),
        migrations.DeleteModel(
            name='Graded',
        ),
        migrations.DeleteModel(
            name='Graded_Questions',
        ),
        migrations.AddField(
            model_name='choice_graded',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher_Framework.Question_Graded'),
        ),
    ]
