# Generated by Django 2.2.13 on 2020-10-06 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher_Framework', '0008_auto_20201006_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLO_Graded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Graded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='question_graded',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Choice_Graded',
        ),
        migrations.DeleteModel(
            name='Question_Graded',
        ),
        migrations.AddField(
            model_name='clo_graded',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher_Framework.Graded'),
        ),
    ]
