# Generated by Django 2.2.13 on 2020-10-07 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher_Framework', '0010_assignment_graded_choice_graded_question_graded'),
    ]

    operations = [
        migrations.CreateModel(
            name='GA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clo_text', models.CharField(max_length=200)),
                ('marks', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher_Framework.GA')),
            ],
        ),
        migrations.RemoveField(
            model_name='choice_graded',
            name='question',
        ),
        migrations.DeleteModel(
            name='Assignment_Graded',
        ),
        migrations.DeleteModel(
            name='Choice_Graded',
        ),
        migrations.DeleteModel(
            name='Question_Graded',
        ),
    ]
